src/components/ui/Button.tsx
공통 컴포넌트 Button 
어떤 변경 사항이 있나요?
사용 시 className으로 크기 및 세부 padding은 추가 조정해서 사용해주세요
=> Feat: 버튼 컴포넌트 생성

src/app/layout.tsx, src/components/common/Header.tsx, src/components/ui/Input.tsx
헤더 추가
어떤 변경 사항이 있나요?
글꼴추가 나중에해야합니다.
=> Feat : 헤더 추가

src/components/common/Footer.tsx
공통 컴포넌트 Footer 추가했습니다 
어떤 변경 사항이 있나요?
추가 조정 필요하시면 말씀해주세요
=> Feat: Footer 추가

src/components/admin/AchievementManage.tsx, src/components/admin/CategoryAddCard.tsx, src/components/admin/CategoryManage.tsx, src/components/admin/ReportTable.tsx, src/components/admin/SharedMapStats.tsx, src/components/admin/UserManagement.tsx
어떤 변경 사항이 있나요?
화면이 한번에 잘 안담겨서 90%로 축소하고 캡쳐한 거라 조금 작아 보일 수 있습니다. 임의로 더미 데이터 넣어서 열고 닫는 효과 해뒀습니다. 나중에 기능 개발하실 때 지우시면 됩니다. 두 번째 코드 사진은 관리자 페이지 개발 시 컴포넌트들 정렬할 때 도움이 될 거라 생각하고 올렸습니다.
=> Feat: 관리자 페이지에 필요한 컴포넌트들 추가

src/app/(main)/sharemap/shareadd/page.tsx, src/app/page.tsx, src/components/common/modal/QuestWrite.tsx, src/components/dashboard/WriteButton.tsx, src/components/sharemap/ShareMapAdd.tsx
등록페이지 퍼블리싱 완료
어떤 변경 사항이 있나요?
일요일 6시에 일괄pr해서 정리해보겠습니다.
=> Style : 공유지도 등록페이지 퍼블리싱

src/app/page.tsx, src/components/mypage/Mypagelabel.tsx, src/components/mypage/ProfileEditModal.tsx
마이페이지 - 프로필 수정 모달 퍼블리싱
- 프로필 이미지 변경 미리보기
- 사용자 이름 수정
어떤 변경 사항이 있나요?
=> style: 프로필 수정 모달 퍼블리싱

src/components/sharemap/ShareClickDetail.tsx, src/components/sharemap/ShareMapDetail.tsx, src/components/sharemap/ShareMapJoin.tsx
버튼에 라우팅 설정 변경된 라우팅에 맞게 다시 설정했습니다. 
어떤 변경 사항이 있나요?
참여하고 완료 누르면 게시글로 가구요. 참여하고 취소 누르면 다시 참여 페이지로 갑니다. 
=> Fix: 라우팅 수정

src/components/sharemap/ShareClickDetail.tsx, src/components/sharemap/ShareMapAdd.tsx, src/components/sharemap/ShareMapJoin.tsx
공유지도 작성 페이지 오른쪽 사이드 공간에 스크롤, 해시태그 추가
공유 지도 상세, 수정(참여) 페이지에 현재 페이지 표시, 사용자 프로필 추가
어떤 변경 사항이 있나요?
예빈님이 올리신 거 참고해서 디자인 수정했고 mb-6 주니까 너무 간격이 벌어진 거 같아서 mb-5로 수정했습니다. 
수정사항생기면 말씀해주세요.
=> Fix: 스크롤 추가

src/components/search/SearchCategoryGroup.tsx, src/components/search/SearchInput.tsx, src/components/search/SearchResultSection.tsx
- 검색어 있을 때 검색 아이콘 색상 진하게
- 검색 결과창에서 스크롤 이상한거 고침
- 전체보기 클릭해서 카테고리별 결과 페이지로 이동하는거 
- 검색 결과창에서 검색어를 지우면 최근 검색어 내역이 안 보이는 버그 수정
- 검색 결과창에서 3~4개씩만 보여지게
어떤 변경 사항이 있나요?
=> Fix : Search

next.config.ts, src/app/(admin)/admin/sharemap/page.tsx, src/components/admin/CategoryCard.tsx, src/components/admin/CategoryManage.tsx, src/components/admin/MarkerManage.tsx, src/components/admin/ReportDetailModal.tsx, src/components/admin/ReportTable.tsx, src/components/admin/SharedMapStats.tsx, src/components/admin/SharemapManage.tsx, src/components/admin/UserManagement.tsx, src/components/common/Header.tsx, src/types/admin.ts
관리자쪽 연결할수있는것은 다 연결
어떤 변경 사항이 있나요?
아직 상세보기의 지도,이미지 넣기는 연결하지못했습니다.(예제 이미지가없기도해서)
사용자쪽 블랙리스트와 관리자권한은 나중에 get을 put으로 바꿔줘야한다.
카테고리쪽은 실제값이 와야 추가가될지 확인을 못해봄 - 커스텀,업적은 api올라오면 해볼예정
공유지도는 참여율이 아직없어서 기다리고 생성도 마찬가지 나머지는 다 구현완료
하드코딩한상태라 코드가 좀 지저분합니다. 
=> Feat : 관리자 Api연결(60% 구현완료)

package-lock.json, package.json, src/components/sharemap/GoogleMapWrapper.tsx, src/components/sharemap/ShareMapAdd.tsx, src/components/sharemap/ShareMapJoin.tsx, src/components/ui/layer/ShareLayerEdit.tsx, src/components/ui/layer/ShareMarkerEdit.tsx, src/libs/api.ts, src/libs/geocode.ts, src/libs/liveblocksClient.ts, src/store/useStore.ts
공유 지도 주소 찾기로 마커 추가하기
어떤 변경 사항이 있나요?
공유 지도 참여 페이지에 주소 찾기로 마커 추가하는 거 기능 구현했습니다. 
코드 수정 좀 해야 하지만 중간 제출때문에 일단 제출했습니다.
=> Feat: 공유 지도 참여 페이지 주소로 마커 추가하기

src/components/mypage/MypageLabel.tsx, src/components/mypage/ProfileEditModal.tsx, src/components/mypage/profiletab/InterestTab.tsx, src/store/profileeditStore.ts, src/types/myprofile.ts
관심분야추가
어떤 변경 사항이 있나요?
관심분야 추가했습니다.
=> Feat : 마이페이지 관심분야 추가

src/app/(main)/dashbord/roadmap/detail/[id]/page.tsx, src/components/loadmap/LoadMapDetail.tsx
로드맵 디테일 페이지 들어갈 수 있도록  axiosInstance 적용해두었습니다. 타입은 아직 정리가 하나도 안된상태라 참고하여 확인해주세요
어떤 변경 사항이 있나요?
=> feat: axiosInstance 적용

package-lock.json, src/components/landingpage/LandingHeader.tsx, src/components/landingpage/LandingScrollSection.tsx, src/components/landingpage/ScrollStep.tsx
- 랜딩페이지 뒤로가기 버튼 클릭 시 오류 발생하던거 수정했습니다! 
어떤 변경 사항이 있나요?
[Screenshot 2025-07-24 at 01.39.03.webm](https://github.com/user-attachments/assets/4dffebba-f3f1-4c1c-80c0-43e7d76127a0)
- 수정하는김에 Image 태그 콘솔 경고창 뜨는거 해결해놨습니다 
=> Fix : 랜딩페이지 버그 수정 

src/libs/mainDashboard.ts
- 퀘스트쪽 토큰 넣어야하는거로 변경되서 axios 사용하는거로 변경 
어떤 변경 사항이 있나요?
- 인기 카테고리 쪽은 수정되면 확인해보겠습니다 
=> Fix : 메인 대시보드 퀘스트 수정

src/app/(main)/dashbord/sharemap/page.tsx, src/components/sharemap/GoogleMapWrapper.tsx, src/components/sharemap/ShareClickDetail.tsx, src/components/sharemap/ShareMapAdd.tsx, src/components/sharemap/ShareMapCardList.tsx, src/components/sharemap/ShareMapDashboard.tsx, src/components/sharemap/ShareMapDetail.tsx, src/components/sharemap/ShareMapJoin.tsx, src/components/ui/card/ShareMapCard.tsx, src/components/ui/layer/ShareLayerEdit.tsx, src/components/ui/layer/ShareMarkerEdit.tsx, src/libs/geocode.ts, src/store/useShareStore.ts, src/types/share.ts, src/types/type.ts
공유 지도 대시보드, 생성, 상세, 지도 상세, 참여 페이지 2차 완료 파일입니다.
어떤 변경 사항이 있나요?
공유 지도 대시보드, 생성, 상세, 지도 상세, 참여 페이지 2차 완료 파일입니다.
너무 많아서 스샷은 다 못찍었고 큼직큼직한 기능들은 완료한 상태고 짜잘한 버그나 빠트린 기능들 좀만 추가하면 될 거 같습니다.
=> Feat: 공유 지도 2차 완료본

src/components/common/Header.tsx, src/components/mypage/profiletab/AchievementTab.tsx, src/hooks/useAchievements.ts, src/libs/achievement.ts, src/store/useAchievementStore.ts, src/types/myprofile.ts
업적 달성 시 관련 토스트 메시지 뜨도록
어떤 변경 사항이 있나요?
지금 이미지처럼 뜨는데, 리팩토링 과정에서 기존 달성한 업적에서 새로 달성한 업적 한개만 뜨도록 변경하겠습니다.
- 추후 업적 조건 마다 리패치 예정
=> feat : 업적 토스트 메시지 구현

src/app/(main)/dashbord/sharemap/detail/layout.tsx, src/app/(main)/dashbord/sharemap/write/layout.tsx, src/components/sharemap/GoogleMapWrapper.tsx, src/components/sharemap/ShareClickDetail.tsx, src/components/sharemap/ShareMapDetail.tsx
이렇게 하면 중복 로드 오류 안떠요.
어떤 변경 사항이 있나요?
이거 merge하고 다시 해보시면 될 겁니다.
=> Fix: 지도 중복 로드 수정

src/components/loadmap/LoadMapDetail.tsx, src/components/quest/QuestDetailPlay.tsx
=> Fix: 오타,오류 수정

src/components/comment/CommentForm.tsx, src/components/common/modal/QuestWrite.tsx, src/components/loadmap/LoadMapWrite.tsx
- 댓글, 로드맵 등록, 퀘스트 등록 에 추가적으로 연결해뒀습니다 
어떤 변경 사항이 있나요?
=> Refact 업적 관련 토스트 

src/app/(main)/dashbord/page.tsx, src/components/maindashbord/ExplorebyTheme.tsx, src/components/maindashbord/HotNow.tsx, src/components/maindashbord/MainDash.tsx, src/components/ui/card/ShareMapCard.tsx, src/libs/mainDashboard.ts
=> Fix : 메인대시보드 1차 수정 완료

src/components/categories/CategorisSetting.tsx, src/components/landingpage/LandingCategoryCard.tsx, src/libs/category.ts
- 원래 fetch 로 토큰으로 요청 보내는게 아니었는데 해당 부분 axios로 수정
- 랜딩 페이지 카테고리쪽도 수정
어떤 변경 사항이 있나요?
=> fix 카테고리 조회쪽 버그 수정 

src/types/authType.ts, src/types/myprofile.ts
=> Fix : 타입 버그 수정

src/components/quest/QuestDetailHeader.tsx
퀘스트 헤더 메뉴 두 개이던 거 수정
어떤 변경 사항이 있나요?
pr 열려있던 거에 마저 push하려고 했는데 머지를 하셨길래 새로 pr 엽니다..
=> Fix: 메뉴 2개 보이던 거 수정

src/components/sharemap/ShareMapAdd.tsx, src/components/sharemap/ShareMapEdit.tsx
해시태그 끝 글자 중복 방지
어떤 변경 사항이 있나요?
해시태그 엔터 시 중복 저장 방지 처리
=> Fix: 해시태그 끝 글자 중복 방지

src/components/sharemap/ShareClickDetail.tsx
디폴트 이미지 추가
어떤 변경 사항이 있나요?
프로필 이미지 없을 때 뜨는 이미지 디폴트 이미지로 변경했습니다.
=> Fix: 디폴트 이미지 추가

src/components/auth/RequireGuest.tsx, src/components/auth/RequireLogin.tsx, src/libs/axios.ts, src/store/useAuthStore.ts
- 엑세스 토큰
- 프로필검증
- 랜딩페이지 
어떤 변경 사항이 있나요?
=> Fix 엑세스 토큰, 프로필검증, 랜딩페이지 

src/components/sharemap/ShareMapDetail.tsx
버그있던 버튼 삭제
어떤 변경 사항이 있나요?
버그 있던 버튼 삭제했습니다.
=> Fix: 버그있던 버튼 삭제

src/components/sharemap/ShareMapJoin.tsx
=> Feat: 신고 아이콘 커서 포인터 추가

src/components/quest/QuestDeatilRanking.tsx, src/components/quest/QuestDetail.tsx, src/components/quest/QuestDetailPlay.tsx, src/components/quest/QuestPlayForm.tsx, src/components/quest/QuestPlayList.tsx, src/components/quest/QuestPlayView.tsx, src/types/type.ts
=> Feat : 퀘스트 여러가지 추가

src/components/dashboard/CardList.tsx, src/components/mypage/MypagePost.tsx, src/types/myprofile.ts
=> Refact : 마이페이지 버그와 전체 카테고리조회 가능

src/components/quest/QuestDetail.tsx, src/components/quest/QuestDetailPlay.tsx, src/components/quest/QuestPlayForm.tsx, src/components/quest/QuestPlayView.tsx, src/libs/mergeSubmission.ts, src/types/type.ts
=> Fix : 퀘스트 부분 수정

src/components/dashboard/EventBox.tsx, src/components/sharemap/ShareMapCardList.tsx, src/components/sharemap/ShareMapDashboard.tsx, src/components/ui/card/ShareMapCard.tsx
셀렉박스 카테고리 조회 방식 변경 및 디자인 수정
어떤 변경 사항이 있나요?
셀렉박스 카테고리 조회 방식 변경 및 디자인 수정했습니당
=> Fix: 셀렉박스 카테고리 조회 방식 변경 및 디자인 수정

src/components/loadmap/RoadMapEdit.tsx
=> fix: 로드맵 수정 카테고리 미선택 경고 추가

src/components/comment/CommentItem.tsx, src/components/sharemap/ShareMapEdit.tsx, src/components/ui/card/ShareMapCard.tsx
공유 지도 쪽 수정 페이지에 토스트 메시지랑 공유 지도 대시보드 카드들 디폴트 이미지 변경, 댓글 메뉴 디자인 변경
어떤 변경 사항이 있나요?
공유 지도 쪽 수정 페이지에 토스트 메시지랑 공유 지도 대시보드 카드들 디폴트 이미지 변경, 댓글 메뉴 디자인 변경했습니다.
=> Design: 토스트 메시지, 디폴트 이미지 변경, 댓글 메뉴 디자인 변경

src/store/useAuthStore.ts
=> Refact 콘솔 지움

src/components/quest/QuestDetail.tsx, src/components/quest/QuestDetailPlay.tsx, src/components/quest/QuestPlayView.tsx, src/types/type.ts
- 퀘스트 정답/오답 판별하는거 작성자만 보이도록 
어떤 변경 사항이 있나요?
=> 퀘스트 작성자는 버튼 안보이도록

src/components/quest/QuestDeatilRanking.tsx, src/components/quest/QuestDetail.tsx, src/components/quest/QuestDetailPlay.tsx, src/components/quest/QuestPlayForm.tsx, src/components/quest/QuestPlayList.tsx, src/types/type.ts
=> Fix : 퀘스트쪽 버그 수정

src/components/quest/QuestDetailPlay.tsx, src/libs/mergeSubmission.ts
=> Fix : 타입버그수정

src/components/auth/RequireGuest.tsx
=> Fix : 어드민이면 로그인카운트 안되게

src/components/mypage/MypageLayer.tsx, src/components/notification/Notification.tsx
=> Fix : 레이어수정 및 알림 수정

src/components/comment/CommentForm.tsx, src/components/maindashbord/HotNow.tsx, src/components/notification/Notification.tsx, src/components/quest/QuestEdit.tsx, src/components/sharemap/ShareMapAdd.tsx, src/components/ui/card/RoadMapCard.tsx, src/components/ui/layer/ShareMarkerEdit.tsx, src/libs/geocode.ts, src/store/useShareStore.ts
=> 콘솔제거 및 버그수정

src/components/ui/layer/MarkerDetail.tsx
=> fix: overflow 조절

src/components/mypage/ProfileEditModal.tsx, src/store/useAuthStore.ts
=> Fix : 비밀번호 확인오류 수정

src/app/(main)/dashbord/sharemap/detail/layout.tsx, src/components/comment/Comment.tsx, src/components/comment/CommentList.tsx, src/components/common/modal/ConfirmModal.tsx, src/components/common/modal/UserModal.tsx, src/components/dashboard/Banner.tsx, src/components/landingpage/LandingCategoryCard.tsx, src/components/landingpage/ScrollStep.tsx, src/components/loadmap/RoadMapEdit.tsx, src/components/maindashbord/SkeletonCategoryCard.tsx, src/components/notification/NotiListItem.tsx, src/components/quest/QuestDetail.tsx, src/components/quest/QuestDetailPlay.tsx, src/components/quest/QuestPlayForm.tsx, src/components/quest/QuestPlayList.tsx, src/components/quest/QuestPlayView.tsx, src/components/search/SearchModal.tsx, src/components/ui/PasswrodInput.tsx, src/hooks/useHashtags.ts, src/libs/mergeSubmission.ts, src/store/useAchievementStore.ts, src/types/comment.ts, src/types/myprofile.ts, src/types/notiType.ts, src/types/quest.ts, src/types/roadmap.ts, src/types/search.ts, src/types/type.ts
=> Refact : 마지막 여러가지 리팩토링

src/libs/auth.ts
어떤 변경 사항이 있나요?
[Screenshot 2025-08-02 at 14.12.26.webm](https://github.com/user-attachments/assets/e6eace4a-acc3-4506-a3cf-156a1a14cc8e)
- 회원가입 성공하면 로그인 페이지로 잘 넘어가는데 로컬 끊어놨었네요;;ㅎ
[Screenshot 2025-08-02 at 14.14.17.webm](https://github.com/user-attachments/assets/db8af9a2-be61-4ca1-9f4d-c1083653bf04)
- 로그인 유효성 
=> Refact 회원 유효성 관련 추가

src/app/(main)/dashbord/roadmap/detail/[id]/preview/page.tsx, src/components/comment/CommentItem.tsx, src/components/common/modal/QuestWrite.tsx, src/components/dashboard/CardList.tsx, src/components/dashboard/WriteButton.tsx, src/components/loadmap/LoadMapDetail.tsx, src/components/loadmap/LoadMapWrite.tsx, src/components/quest/QuestDeatilRanking.tsx, src/components/quest/QuestDetail.tsx, src/components/quest/QuestDetailHeader.tsx, src/components/quest/QuestDetailPlay.tsx, src/components/quest/QuestPlayForm.tsx, src/components/quest/QuestPlayList.tsx, src/components/sharemap/ShareMapAdd.tsx, src/components/sharemap/ShareMapDetail.tsx, src/store/useQuestStore.ts, src/types/myprofile.ts, src/types/quest.ts, src/types/type.ts
=> Refact : 여러가지 수정들

src/components/quest/QuestDetailPlay.tsx, src/components/quest/QuestPlayList.tsx, src/types/quest.ts
=> Fix : 작성자도 참여하기 안뜨게 수정

src/components/mypage/ProfileEditModal.tsx
=> Fix : 변경내용없으면 없다고 안내 추가 수정

src/components/quest/QuestDeatilRanking.tsx, src/components/quest/skeleton/QuestDetailRankingSkeleton.tsx
=> Feat : 랭킹에 스켈레톤 추가

src/components/comment/Comment.tsx
댓글 생성 시 댓글 리스트의 첫번째로 가는 버그 해결했습니다.
어떤 변경 사항이 있나요?
=> fix: 댓글 생성 ui 수정

src/components/sharemap/ShareClickDetail.tsx, src/components/sharemap/ShareMapJoin.tsx
=> Fix : 로딩쪽 수정

src/components/sharemap/GoogleMapWrapper.tsx, src/components/sharemap/ShareClickDetail.tsx, src/components/sharemap/ShareMapDetail.tsx, src/components/ui/card/ShareMapCard.tsx
댓글, 지도 줌 수정
어떤 변경 사항이 있나요?
지도 줌 사이즈 변경, 공유지도 댓글 섹션 사이즈 변경
=> Fix: 2차 수정(댓글, 지도 줌)

src/components/comment/CommentItem.tsx
=> fix: 게시글 작성자 댓글 삭제만. 수정하기 뺌

src/components/comment/CommentItem.tsx
=> fix: 댓글 수정/삭제 중복 조건 제거
